name: Codecov

on:
  push:
    branches:
      [master, refactor]
  pull_request:
    branches:
      [master, refactor]

jobs:
  env-details:
    name: Environment details
    runs-on: macOS-latest
    steps:
      - name: xcode version
        run: xcodebuild -version -sdk

      - name: list simulators
        run: |
          xcrun simctl delete unavailable
          xcrun simctl list
  build:
    runs-on: macOS-latest
    steps:
      - name: Test
        uses: actions/checkout@v1
      - name: Build and Test
        run:  |
          set -o pipefail
          xcodebuild clean test \
            -workspace Example/TwitchAPIWrapper.xcworkspace \
            -scheme TwitchAPIWrapper-Example \
            -sdk iphonesimulator14.4 \
            -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.4' \
            -enableCodeCoverage YES
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.2.1
