name: TwitchAPIWrapper Codecov

on:
  push:
    branches:
      [master, refactor]
  pull_request:
    branches:
      [master, refactor]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Test
        uses: actions/checkout@v1
      - name: Build and Test
        run:  xcodebuild test -workspace Example/TwitchAPIWrapper.xcworkspace -scheme TwitchAPIWrapper-Example -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.5' -enableCodeCoverage YES  build test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.2.1
