 GitHub Actions Virtual Environments
# https://github.com/actions/virtual-environments/

# A template workflow intended for Apple Platform libraries

name: CI

on:
  push:
    branches:
      [master, refactor]
    paths:
      - '.github/workflows/ci.yml'
      - 'Sources/**/*.*'
      - 'Tests/**/*.*'
      - 'Example/**/*.*'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/ci.yml'
      - 'Sources/**/*.*'
      - 'Tests/**/*.*'
      - 'Example/**/*.*'
